val_set_json: /oak/stanford/groups/mignot/projects/actigraphy_fm/data/splits/rbd/other/test_files.json

#Use model trained on all internal training and validation sets
model_base_dir: /oak/stanford/groups/mignot/projects/actigraphy_fm/runs/wassed/finetune_cv/mae_bwm_external_4019671/
results_path: /oak/stanford/groups/mignot/projects/actigraphy_fm/results/accelerest_rbd/other/

ft_epoch: 100

# Model params
n_classes: 4
patch_size: 900
in_channels: 3
embed_dim: 256
num_heads: 8
mlp_ratio: 2
num_layers: 12
max_seq_len: 256
num_lstm_layers: 0
lstm_dim: 0 # 0 
head: linear